### ISSUE TITLE
NTRUParameters EES743EP1 

### ISSUE THREAD

**Issue by Noc2** [Steppenwolfe65/NTRU-NET#1]
First of all, thank you for your great work! 
Since security innovation [released their patents](https://www.securityinnovation.com/company/news-and-events/press-releases/security-innovation-makes-ntruencrypt-patent-free), I would like to implement EES743EP1 into your code (https://eprint.iacr.org/2015/708.pdf or https://github.com/tbuktu/libntru/blob/master/src/encparams.c). 
Would it be correct to do it like this:
`public static readonly NTRUParameters EES743EP1 = new NTRUParameters(new byte[] { 2, 2, 2, 106 }, 743, 2048, 11, 11, 15, 204, 106, 256, 13, 12, 7, true, false, true, Digests.SHA256, Prngs.CTRPrng);` or am I missing something here?

**Comment by Steppenwolfe65** [comment]
I can't support anything but the existing param sets, why not use one of them? This is a few years old and it's been a long time since I looked at this code, so.. you're on your own as far as that goes.

I consider the C# version of CEX, from which this was pulled, to be all but officially retired, and it will soon be replaced entirely by the C++ version, which is a far safer, faster, and more secure set of implementations. 
The good news is, if you are a C# programmer, you will be able to use that library through a managed wrapper library, the bad news is, that's still about 8-12 months away. 

I now feel that interpreted languages are a poor choice for cryptographic primitives, because of timing issues and a lack of access to lower-level instructions.
Also, in this implementation, C# is limited to using cryptgenrandom to create seed material, this is a 'black-box' and as such can not be fully trusted. 
There has also been a great deal of disruption to lattice-based cryptography in the last couple of years, and advances in cryptanalysis may at some point undermine the security of this form of NTRU.

A new version of this cipher was submitted to the NIST PQ call; NTRU Prime, and that addresses some of these weaknesses, and could prove to be the successor to this older version.
https://csrc.nist.gov/Projects/Post-Quantum-Cryptography/Round-1-Submissions

HTH,
John

**Comment by Noc2** [comment]
Thanks for the fast and very helpful reply. The main reason I am looking into it, is simply to learn more about it.
